/**
 * App-wide constants
 */
export const DISCOVERY_RADIUS = 30; // Default discovery radius in meters

export const NAVIGATION_TRUST = {
  MAX_LOCATION_AGE_MS: 15000,
  MAX_LOCATION_JUMP_METERS: 100,
  MAX_PLAUSIBLE_SPEED_MPS: 12,
  MAX_JUMP_SPEED_MPS: 25,
  LOG_DUPLICATE_WINDOW_MS: 8000,
  LOW_TRUST_THRESHOLD: 40,
};

export const GUIDANCE_MODE = {
  COMPASS: 'compass',
  GPS_FALLBACK: 'gps-fallback',
  ROUTE: 'route',
  SENSOR_LIMITED: 'sensor-limited',
};

export const EVENT_SETTINGS = {
  DEFAULT_DISCOVERY_RADIUS_METERS: DISCOVERY_RADIUS,
};

export const LOCATION_PERMISSIONS = {
  HIGH_ACCURACY: true,
  TIME_INTERVAL: 5000, // Update every 5 seconds
  DISTANCE_INTERVAL: 5, // Or every 5 meters
};

export const MAP_REGION = {
  LATITUDE_DELTA: 0.01, // Zoomed in a bit closer for walking
  LONGITUDE_DELTA: 0.01,
};

export const PLAYER_ID = 3; // Dummy player ID for testing

export const COMPASS_SETTINGS = {
  ON_TARGET_THRESHOLD_DEGREES: 5,
  UPDATE_INTERVAL_MS: 1000,
};

export const CAMERA_CAPTURE_SETTINGS = {
  ALLOWS_EDITING: true,
  ASPECT: [4, 3],
  QUALITY: 0.7,
};

export const MOTION_FEATURES = {
  ENABLE_ACCELEROMETER: true,
  ENABLE_PEDOMETER: false,
};

export const ACCELEROMETER_SETTINGS = {
  UPDATE_INTERVAL_MS: 300,
  SMOOTHING_FACTOR: 0.2,
  STATIONARY_THRESHOLD: 0.08,
  ACTIVE_MOVEMENT_THRESHOLD: 0.22,
};

export const STEP_COUNTER_SETTINGS = {
  DEFAULT_DAILY_STEP_GOAL: 5000,
  MIN_STEPS_FOR_MOVEMENT_CONFIDENCE: 20,
  SESSION_RESET_ON_APP_START: true,
};

export const MOTION_GUIDANCE_SETTINGS = {
  HINT_DEBOUNCE_MS: 700,
  LOW_MOVEMENT_INTENSITY_THRESHOLD: 0.1,
};

export const GUIDANCE_STATUS_TEXT = {
  ALIGNING: 'Adjusting heading',
  ALIGNED: 'On target',
  CALIBRATING: 'Compass calibrating.',
  SENSOR_LIMITED: 'Compass limited. Use GPS fallback.',
};

export const MOTION_GAMEPLAY_SETTINGS = {
  ENABLE_MOVEMENT_CONFIDENCE: true,
  SHOW_CONFIDENCE_IN_SUCCESS_MESSAGE: true,
  LOW_CONFIDENCE_THRESHOLD: 40,
  HIGH_CONFIDENCE_THRESHOLD: 75,
};
