import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  targetPanel: {
    position: 'absolute',
    bottom: 40,
    left: 20,
    right: 20,
    zIndex: 12,
    maxWidth: '90%',
    alignSelf: 'center',
    backgroundColor: 'white',
    padding: 20,
    borderRadius: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 12,
  },
  panelHandleRow: {
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    minHeight: 32,
    paddingVertical: 4,
    marginBottom: 8,
    gap: 8,
  },
  panelDragHandleArea: {
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 24,
    marginBottom: 4,
  },
  panelHandle: {
    width: 46,
    height: 5,
    borderRadius: 3,
    backgroundColor: '#d1d5db',
    marginBottom: 6,
  },
  panelToggleButton: {
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 999,
    backgroundColor: '#f3f4f6',
  },
  panelToggleText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#374151',
  },
  panelStateIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    marginLeft: 8,
  },
  stateIndicatorDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#d1d5db',
  },
  stateIndicatorDot_active: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#2563eb',
  },
  panelTitle: { fontSize: 18, fontWeight: 'bold' },
  expandedContentContainer: {
    flex: 1,
  },
  expandedContentContainer_half: {
    maxHeight: 300,
  },
  expandedContentScroll: {
    paddingBottom: 12,
  },
  collapsedSummaryContainer: {
    paddingBottom: 4,
  },
  collapsedSummaryContainer_info: {
    backgroundColor: '#f5f8ff',
  },
  collapsedSummaryContainer_warning: {
    backgroundColor: '#fffbeb',
  },
  collapsedSummaryContainer_success: {
    backgroundColor: '#ecfdf5',
  },
  collapsedSummaryContainer_error: {
    backgroundColor: '#fef2f2',
  },
  collapsedDistanceText: {
    fontSize: 15,
    color: '#4b5563',
    marginTop: 4,
  },
  collapsedRouteText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#2563eb',
    marginTop: 4,
  },
  collapsedRouteText_info: {
    color: '#2563eb',
  },
  collapsedRouteText_success: {
    color: '#166534',
  },
  collapsedRouteText_warning: {
    color: '#b45309',
  },
  collapsedRouteText_error: {
    color: '#b91c1c',
  },
  collapsedTrendText: {
    fontSize: 12,
    fontWeight: '700',
    marginTop: 4,
  },
  collapsedTrendText_info: {
    color: '#2563eb',
  },
  collapsedTrendText_success: {
    color: '#166534',
  },
  collapsedTrendText_warning: {
    color: '#b45309',
  },
  collapsedHintText: {
    fontSize: 12,
    color: '#2563eb',
    marginTop: 4,
    fontWeight: '600',
  },
  collapsedHintText_info: {
    color: '#2563eb',
  },
  collapsedHintText_warning: {
    color: '#b45309',
  },
  collapsedHintText_success: {
    color: '#166534',
  },
  collapsedHintText_error: {
    color: '#b91c1c',
  },
  panelDistance: { fontSize: 16, marginVertical: 10, color: '#555' },
  routeSummaryText: {
    fontSize: 12,
    color: '#334155',
    fontWeight: '700',
    marginBottom: 8,
  },
  routeErrorText: {
    fontSize: 12,
    color: '#b45309',
    fontWeight: '700',
    marginBottom: 8,
  },
  distanceTrendText: {
    fontSize: 12,
    fontWeight: '700',
    marginTop: -2,
    marginBottom: 8,
  },
  distanceTrendText_info: {
    color: '#2563eb',
  },
  distanceTrendText_success: {
    color: '#166534',
  },
  distanceTrendText_warning: {
    color: '#b45309',
  },
  guidanceWarningText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#b45309',
    backgroundColor: '#fffbeb',
    borderColor: '#fde68a',
    borderWidth: 1,
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 10,
    marginBottom: 10,
  },
  directionContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 10,
    padding: 10,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#dbeafe',
    backgroundColor: '#f5f8ff',
  },
  directionContainer_info: {
    backgroundColor: '#f5f8ff',
    borderColor: '#dbeafe',
  },
  directionContainer_warning: {
    backgroundColor: '#fffbeb',
    borderColor: '#fde68a',
  },
  directionContainer_success: {
    backgroundColor: '#ecfdf5',
    borderColor: '#bbf7d0',
  },
  directionContainer_error: {
    backgroundColor: '#fef2f2',
    borderColor: '#fecaca',
  },
  arrowContainer: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
    backgroundColor: '#e6eeff',
  },
  arrowContainer_info: { backgroundColor: '#e6eeff' },
  arrowContainer_warning: { backgroundColor: '#fef3c7' },
  arrowContainer_success: { backgroundColor: '#dcfce7' },
  arrowContainer_error: { backgroundColor: '#fee2e2' },
  arrowText: {
    fontSize: 26,
    color: '#1e5aa8',
    fontWeight: 'bold',
    lineHeight: 28,
  },
  arrowText_info: { color: '#1e5aa8' },
  arrowText_warning: { color: '#b45309' },
  arrowText_success: { color: '#166534' },
  arrowText_error: { color: '#b91c1c' },
  directionTextContainer: {
    flex: 1,
  },
  directionTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: '#1e5aa8',
    marginBottom: 2,
  },
  directionHint: {
    fontSize: 15,
    fontWeight: '600',
    color: '#1f2937',
  },
  directionMeta: {
    fontSize: 12,
    color: '#6b7280',
    marginTop: 2,
  },
  motionContainer: {
    borderRadius: 10,
    padding: 10,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    backgroundColor: '#f6f7f9',
  },
  motionContainer_info: {
    backgroundColor: '#f6f7f9',
    borderColor: '#e5e7eb',
  },
  motionContainer_warning: {
    backgroundColor: '#fffbeb',
    borderColor: '#fde68a',
  },
  motionContainer_success: {
    backgroundColor: '#ecfdf5',
    borderColor: '#bbf7d0',
  },
  motionContainer_error: {
    backgroundColor: '#fef2f2',
    borderColor: '#fecaca',
  },
  motionTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: '#334155',
    marginBottom: 2,
  },
  statusPill: {
    alignSelf: 'flex-start',
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 999,
    marginTop: 6,
    marginBottom: 6,
  },
  statusPill_info: { backgroundColor: '#dbeafe' },
  statusPill_warning: { backgroundColor: '#fde68a' },
  statusPill_success: { backgroundColor: '#bbf7d0' },
  statusPill_error: { backgroundColor: '#fecaca' },
  statusPillText: {
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.2,
  },
  statusPillText_info: { color: '#1d4ed8' },
  statusPillText_warning: { color: '#92400e' },
  statusPillText_success: { color: '#166534' },
  statusPillText_error: { color: '#991b1b' },
  motionStatus: {
    fontSize: 14,
    color: '#111827',
    fontWeight: '600',
  },
  motionMeta: {
    fontSize: 12,
    color: '#6b7280',
    marginTop: 2,
  },
  motionAdvisory: {
    marginTop: 6,
    fontSize: 12,
    color: '#1d4ed8',
    fontWeight: '600',
  },
  proofContainer: {
    marginBottom: 12,
    borderRadius: 10,
    borderWidth: 1,
    padding: 10,
    backgroundColor: '#f9fafb',
    borderColor: '#e5e7eb',
  },
  proofContainer_info: {
    backgroundColor: '#f9fafb',
    borderColor: '#e5e7eb',
  },
  proofContainer_warning: {
    backgroundColor: '#fffbeb',
    borderColor: '#fde68a',
  },
  proofContainer_success: {
    backgroundColor: '#ecfdf5',
    borderColor: '#bbf7d0',
  },
  proofContainer_error: {
    backgroundColor: '#fef2f2',
    borderColor: '#fecaca',
  },
  proofTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#111827',
  },
  proofHeaderButton: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  proofHeaderTextWrap: {
    flexShrink: 1,
    paddingRight: 10,
  },
  proofHeaderHint: {
    marginTop: 2,
    fontSize: 11,
    color: '#6b7280',
    fontWeight: '600',
  },
  proofHeaderRight: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  proofChevron: {
    marginLeft: 8,
    fontSize: 16,
    color: '#4b5563',
    fontWeight: '700',
    minWidth: 12,
    textAlign: 'center',
  },
  proofExpandedContent: {
    marginTop: 8,
  },
  proofBusyText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#1d4ed8',
    marginTop: 6,
    marginBottom: 8,
  },
  proofSubtitle: {
    fontSize: 12,
    color: '#6b7280',
    marginTop: 3,
    marginBottom: 8,
  },
  proofPreview: {
    width: '100%',
    height: 120,
    borderRadius: 8,
    marginBottom: 8,
    backgroundColor: '#e5e7eb',
  },
  proofErrorText: {
    color: '#b91c1c',
    fontSize: 12,
    marginBottom: 8,
  },
  proofButtonRow: {
    flexDirection: 'row',
    alignItems: 'center',
    columnGap: 8,
  },
  captureButton: {
    flex: 1,
    backgroundColor: '#2563eb',
    paddingVertical: 10,
    borderRadius: 8,
    alignItems: 'center',
  },
  captureButtonDisabled: {
    backgroundColor: '#93c5fd',
  },
  captureButtonText: {
    color: '#ffffff',
    fontWeight: '700',
    fontSize: 14,
  },
  clearProofButton: {
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#d1d5db',
    backgroundColor: '#ffffff',
  },
  clearProofButtonText: {
    fontSize: 13,
    color: '#374151',
    fontWeight: '600',
  },
  logButton: {
    backgroundColor: '#28a745',
    padding: 15,
    borderRadius: 10,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#28a745',
  },
  logButton_info: { backgroundColor: '#28a745', borderColor: '#28a745' },
  logButton_warning: { backgroundColor: '#d97706', borderColor: '#d97706' },
  logButton_success: { backgroundColor: '#059669', borderColor: '#059669' },
  logButton_error: { backgroundColor: '#dc2626', borderColor: '#dc2626' },
  logButtonDisabled: { backgroundColor: '#cccccc', borderColor: '#cccccc' },
  logButtonText: { color: 'white', fontWeight: 'bold', fontSize: 16 },
  logButtonMeta: {
    marginBottom: 8,
    fontSize: 12,
    fontWeight: '700',
    color: '#6b7280',
    textAlign: 'center',
  },
  logButtonMeta_warning: { color: '#b45309' },
  logButtonMeta_success: { color: '#166534' },
  logButtonMeta_error: { color: '#b91c1c' },
  logButtonMeta_info: { color: '#6b7280' },
});

export default styles;
