import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  targetPanel: {
    position: 'absolute',
    bottom: 40,
    left: 20,
    right: 20,
    backgroundColor: 'white',
    padding: 20,
    borderRadius: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  panelHandleRow: {
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 52,
    paddingVertical: 6,
    marginBottom: 8,
  },
  panelHandle: {
    width: 46,
    height: 5,
    borderRadius: 3,
    backgroundColor: '#d1d5db',
    marginBottom: 8,
  },
  panelToggleButton: {
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 999,
    backgroundColor: '#f3f4f6',
  },
  panelToggleText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#374151',
  },
  panelTitle: { fontSize: 18, fontWeight: 'bold' },
  collapsedSummaryContainer: {
    paddingBottom: 4,
  },
  collapsedDistanceText: {
    fontSize: 15,
    color: '#4b5563',
    marginTop: 4,
  },
  collapsedHintText: {
    fontSize: 12,
    color: '#2563eb',
    marginTop: 4,
    fontWeight: '600',
  },
  panelDistance: { fontSize: 16, marginVertical: 10, color: '#555' },
  directionContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f5f8ff',
    borderRadius: 10,
    padding: 10,
    marginBottom: 12,
  },
  arrowContainer: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#e6eeff',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  arrowText: {
    fontSize: 26,
    color: '#1e5aa8',
    fontWeight: 'bold',
    lineHeight: 28,
  },
  directionTextContainer: {
    flex: 1,
  },
  directionTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: '#1e5aa8',
    marginBottom: 2,
  },
  directionHint: {
    fontSize: 15,
    fontWeight: '600',
    color: '#1f2937',
  },
  directionMeta: {
    fontSize: 12,
    color: '#6b7280',
    marginTop: 2,
  },
  motionContainer: {
    backgroundColor: '#f6f7f9',
    borderRadius: 10,
    padding: 10,
    marginBottom: 12,
  },
  motionTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: '#334155',
    marginBottom: 2,
  },
  motionStatus: {
    fontSize: 14,
    color: '#111827',
    fontWeight: '600',
  },
  motionMeta: {
    fontSize: 12,
    color: '#6b7280',
    marginTop: 2,
  },
  motionAdvisory: {
    marginTop: 6,
    fontSize: 12,
    color: '#1d4ed8',
    fontWeight: '600',
  },
  proofContainer: {
    marginBottom: 12,
    backgroundColor: '#f9fafb',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    padding: 10,
  },
  proofTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#111827',
  },
  proofSubtitle: {
    fontSize: 12,
    color: '#6b7280',
    marginTop: 3,
    marginBottom: 8,
  },
  proofPreview: {
    width: '100%',
    height: 120,
    borderRadius: 8,
    marginBottom: 8,
    backgroundColor: '#e5e7eb',
  },
  proofErrorText: {
    color: '#b91c1c',
    fontSize: 12,
    marginBottom: 8,
  },
  proofButtonRow: {
    flexDirection: 'row',
    alignItems: 'center',
    columnGap: 8,
  },
  captureButton: {
    flex: 1,
    backgroundColor: '#2563eb',
    paddingVertical: 10,
    borderRadius: 8,
    alignItems: 'center',
  },
  captureButtonDisabled: {
    backgroundColor: '#93c5fd',
  },
  captureButtonText: {
    color: '#ffffff',
    fontWeight: '700',
    fontSize: 14,
  },
  clearProofButton: {
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#d1d5db',
    backgroundColor: '#ffffff',
  },
  clearProofButtonText: {
    fontSize: 13,
    color: '#374151',
    fontWeight: '600',
  },
  logButton: {
    backgroundColor: '#28a745',
    padding: 15,
    borderRadius: 10,
    alignItems: 'center',
  },
  logButtonDisabled: { backgroundColor: '#cccccc' },
  logButtonText: { color: 'white', fontWeight: 'bold', fontSize: 16 },
});

export default styles;
